apiVersion: batch/v1
kind: Job
metadata:
  name: my-app-job
spec:
  template:
    spec:
      containers:
      - name: myapp-container
        image: rferns/maven-app:latest-k8s
        imagePullPolicy: Never
      restartPolicy: Never
