apiVersion: v1
kind: ServiceAccount
metadata:
  name: myapp-sa
  namespace: dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: dev
  name: myapp-role
rules:
  - apiGroups: [""]       # Core APIs (pods, services, etc.)
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]  # Jobs API
    resources: ["jobs"]
    verbs: ["get", "list", "create", "delete", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: myapp-rolebinding
  namespace: dev
subjects:
  - kind: ServiceAccount
    name: myapp-sa
    namespace: dev
roleRef:
  kind: Role
  name: myapp-role
  apiGroup: rbac.authorization.k8s.io
